### PR TITLE
fix #25

### LINKED ISSUE #25: Error state doesn't work properly if initialized with is-invalid class
If the `mdl-selectfield` div has the `is-invalid` class when the page is loaded, the label is quickly removed and the error state does not display. This is problematic if a form is re-rendered in order to display error messages to the user. The native MDL input components do not have this behavior.

To replicate, simply add the `is-invalid` class to the "with floating label" [codepen](http://codepen.io/mebibou/pen/pjEjOv) example provided in the readme, and watch the preview pane. You'll see it re-initialize with the proper styles, but then quickly (almost imperceptibly) revert back.

I've tried several ways to fix this, but haven't found the solution yet.

### PR DESCRIPTION
**Pull request by mh-cbon**
When `is-invalid` class is statically added to the select field element, the error is displayed.

### CODE REVIEW

File: src/selectfield/selectfield.js [hunk 1]
```diff
@@ -168,8 +168,13 @@
         this.select_.addEventListener('blur', this.boundBlurHandler);
         this.select_.addEventListener('reset', this.boundResetHandler);
 
+        var invalid = this.element_.classList
+          .contains(this.CssClasses_.IS_INVALID);
```
Comment (mebibou) [inline src/selectfield/selectfield.js:172]: What is this `contains` method?

Comment (mh-cbon) [reply src/selectfield/selectfield.js:172]: https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

Comment (mebibou) [reply src/selectfield/selectfield.js:172]: ah yes okay 👍

**Comment by mebibou** [comment]
Could you show me on a plunkr or something what this fixes?

**Comment by mh-cbon** [comment]
Sorry for the missing plunkr,

When a new select is defined, as of today, it is not possible to set its invalid status by adding the class on the element before init happen.

This was not working before the component forcibly removes the class when init occurs.

With this patch, it is possible to add the class in the html, 
and thus display error message and invalid state

``` html
<div class="mdl-selectfield mdl-js-selectfield is-invalid">...</div>
```

This is useful to me because i use this component in non-client side framework, IE a server side framework which generates the components and validate forms on the server side.

Also this change is a copy-cat of the core mdl component textfield. You ll find the exact same code in it.

Some testing may be required to check that nothing else was broken by this addition.

**Comment by mebibou** [comment]
Indeed: https://github.com/google/material-design-lite/commit/096ce16d8181245f7c998d3ee018ba729be86a46

I'll have a look at this tomorrow then, thanks
